import './Experience.scss';
import CSharpLogo from './assets/csharp_semi.png';
import TSAWSLogo from './assets/aws-ts-logo.png';
import AngularLogo from './assets/anguar.png';

type Experience = {
    logo: string;
    type: string;
    description: string;
    tags: string[];
}

const experiences: Experience[] = [
    {
        logo: TSAWSLogo,
        type: "AWS Industrial Data Hub",
        description: "Developed as part of a team using TypeScript. Formatted, processed, stored, and routed data generated by automotive parts manufacturing machines to external services",
        tags: ["TypeScript", "AWS", "Data Processing", "Lambda", "StepFunctions", "S3", "Kinesis"]
    },
    {
        logo: CSharpLogo,
        type: "SEMI Standard Communication Library",
        description: "Co-developed a high-performance C# library for semiconductor manufacturing. Designed state machines and facilitated the manual and automatic transmission of messages based on system states.",
        tags: ["C#", "SEMIStandard", "StateMachine"]
    },
    {
        logo: AngularLogo,
        type: "SEMI Integration Demo",
        description: "Collaborated on a demo environment utilizing the SEMI library.",
        tags: ["Angular", "TypeScript", "C#", "Swagger"]
    }
]

export function Experience() {
    return (
        <div className='about-me_experience-page_container'>
            {experiences.map((experience) => {
                return (
                    <div className='about-me_experience-page_experience_item'>
                        <div className='about-me_experience-page_experience_item_logo'>
                            <img src={experience.logo} alt='' />
                        </div>
                        <div className='about-me_experience-page_experience_item_text'>
                            <h3>{experience.type}</h3>
                            <p>{experience.description}</p>
                            <div className='about-me_experience-page_experience_item_text_tag_container'>
                                {experience.tags.map((tag) => {
                                    return <span key={tag} className='about-me_experience-page_experience_item_text_tag'>&lt;{tag}&gt;</span>
                                })}
                            </div>
                        </div>
                    </div>
                )
            })}
        </div>
    )
}
